export const countyList = [
    { value: 'APPLING', label: 'APPLING' },
    { value: 'ATHENS- CLARKE', label: 'ATHENS- CLARKE' },
    { value: 'ATKINSON', label: 'ATKINSON' },
    { value: 'AUGUSTA- RICHMOND', label: 'AUGUSTA- RICHMOND' },
    { value: 'BACON', label: 'BACON' },
    { value: 'BAKER', label: 'BAKER' },
    { value: 'BALDWIN', label: 'BALDWIN' },
    { value: 'BANKS', label: 'BANKS' },
    { value: 'BARROW', label: 'BARROW' },
    { value: 'BARTOW', label: 'BARTOW' },
    { value: 'BEN HILL', label: 'BEN HILL' },
    { value: 'BERRIEN', label: 'BERRIEN' },
    { value: 'BIBB', label: 'BIBB' },
    { value: 'BLECKLEY', label: 'BLECKLEY' },
    { value: 'BRANTLEY', label: 'BRANTLEY' },
    { value: 'BROOKS', label: 'BROOKS' },
    { value: 'BRYAN', label: 'BRYAN' },
    { value: 'BULLOCH', label: 'BULLOCH' },
    { value: 'BURKE', label: 'BURKE' },
    { value: 'BUTTS', label: 'BUTTS' },
    { value: 'CALHOUN', label: 'CALHOUN' },
    { value: 'CAMDEN', label: 'CAMDEN' },
    { value: 'CANDLER', label: 'CANDLER' },
    { value: 'CARROLL', label: 'CARROLL' },
    { value: 'CATOOSA', label: 'CATOOSA' },
    { value: 'CHARLTON', label: 'CHARLTON' },
    { value: 'CHATHAM', label: 'CHATHAM' },
    { value: 'CHATTOOGA', label: 'CHATTOOGA' },
    { value: 'CHEROKEE', label: 'CHEROKEE' },
    { value: 'CLAY', label: 'CLAY' },
    { value: 'CLINCH', label: 'CLINCH' },
    { value: 'COBB', label: 'COBB' },
    { value: 'COFFEE', label: 'COFFEE' },
    { value: 'COLQUITT', label: 'COLQUITT' },
    { value: 'COLUMBIA', label: 'COLUMBIA' },
    { value: 'COLUMBUS- MUSCOGEE', label: 'COLUMBUS- MUSCOGEE' },
    { value: 'COOK', label: 'COOK' },
    { value: 'COWETA', label: 'COWETA' },
    { value: 'CRAWFORD', label: 'CRAWFORD' },
    { value: 'CRISP', label: 'CRISP' },
    { value: 'CUSSETA- CHATTA HOOCHEE', label: 'CUSSETA- CHATTA HOOCHEE' },
    { value: 'DADE', label: 'DADE' },
    { value: 'DAWSON', label: 'DAWSON' },
    { value: 'DECATUR', label: 'DECATUR' },
    { value: 'DEKALB', label: 'DEKALB' },
    { value: 'DODGE', label: 'DODGE' },
    { value: 'DOOLY', label: 'DOOLY' },
    { value: 'DOUGHERTY', label: 'DOUGHERTY' },
    { value: 'DOUGLAS', label: 'DOUGLAS' },
    { value: 'EARLY', label: 'EARLY' },
    { value: 'ECHOLS', label: 'ECHOLS' },
    { value: 'EFFINGHAM', label: 'EFFINGHAM' },
    { value: 'ELBERT', label: 'ELBERT' },
    { value: 'EMANUEL', label: 'EMANUEL' },
    { value: 'EVANS', label: 'EVANS' },
    { value: 'FANNIN', label: 'FANNIN' },
    { value: 'FAYETTE', label: 'FAYETTE' },
    { value: 'FLOYD', label: 'FLOYD' },
    { value: 'FORSYTH', label: 'FORSYTH' },
    { value: 'FRANKLIN', label: 'FRANKLIN' },
    { value: 'FULTON', label: 'FULTON' },
    { value: 'GEORGETOWN- QUITMAN', label: 'GEORGETOWN- QUITMAN' },
    { value: 'GILMER', label: 'GILMER' },
    { value: 'GLYNN', label: 'GLYNN' },
    { value: 'GORDON', label: 'GORDON' },
    { value: 'GRADY', label: 'GRADY' },
    { value: 'GREENE', label: 'GREENE' },
    { value: 'GWINNETT', label: 'GWINNETT' },
    { value: 'HALL', label: 'HALL' },
    { value: 'HANCOCK', label: 'HANCOCK' },
    { value: 'HARALSON', label: 'HARALSON' },
    { value: 'HARRIS', label: 'HARRIS' },
    { value: 'HART', label: 'HART' },
    { value: 'HEARD', label: 'HEARD' },
    { value: 'HENRY', label: 'HENRY' },
    { value: 'IRWIN', label: 'IRWIN' },
    { value: 'JACKSON', label: 'JACKSON' },
    { value: 'JASPER', label: 'JASPER' },
    { value: 'JEFF DAVIS', label: 'JEFF DAVIS' },
    { value: 'JEFFERSON', label: 'JEFFERSON' },
    { value: 'JENKINS', label: 'JENKINS' },
    { value: 'JOHNSON', label: 'JOHNSON' },
    { value: 'JONES', label: 'JONES' },
    { value: 'LANIER', label: 'LANIER' },
    { value: 'LAURENS', label: 'LAURENS' },
    { value: 'LEE', label: 'LEE' },
    { value: 'LIBERTY', label: 'LIBERTY' },
    { value: 'LINCOLN', label: 'LINCOLN' },
    { value: 'LONG', label: 'LONG' },
    { value: 'LOWNDES', label: 'LOWNDES' },
    { value: 'LUMPKIN', label: 'LUMPKIN' },
    { value: 'MACON', label: 'MACON' },
    { value: 'MADISON', label: 'MADISON' },
    { value: 'MARION', label: 'MARION' },
    { value: 'McINTOSH', label: 'McINTOSH' },
    { value: 'MERIWETHER', label: 'MERIWETHER' },
    { value: 'MILLER', label: 'MILLER' },
    { value: 'MITCHELL', label: 'MITCHELL' },
    { value: 'MONROE', label: 'MONROE' },
    { value: 'MORGAN', label: 'MORGAN' },
    { value: 'MURRAY', label: 'MURRAY' },
    { value: 'NEWTON', label: 'NEWTON' },
    { value: 'OCONEE', label: 'OCONEE' },
    { value: 'OGLETHORPE', label: 'OGLETHORPE' },
    { value: 'PAULDING', label: 'PAULDING' },
    { value: 'PEACH', label: 'PEACH' },
    { value: 'HOUSTON', label: 'HOUSTON' },
    { value: 'PICKENS', label: 'PICKENS' },
    { value: 'PIERCE', label: 'PIERCE' },
    { value: 'PIKE', label: 'PIKE' },
    { value: 'LAMAR', label: 'LAMAR' },
    { value: 'POLK', label: 'POLK' },
    { value: 'PULASKI', label: 'PULASKI' },
    { value: 'PUTNAM', label: 'PUTNAM' },
    { value: 'RABUN', label: 'RABUN' },
    { value: 'RANDOLPH', label: 'RANDOLPH' },
    { value: 'SCHLEY', label: 'SCHLEY' },
    { value: 'SCREVEN', label: 'SCREVEN' },
    { value: 'SEMINOLE', label: 'SEMINOLE' },
    { value: 'SPALDING', label: 'SPALDING' },
    { value: 'STEWART', label: 'STEWART' },
    { value: 'SUMTER', label: 'SUMTER' },
    { value: 'TALBOT', label: 'TALBOT' },
    { value: 'TATTNALL', label: 'TATTNALL' },
    { value: 'TAYLOR', label: 'TAYLOR' },
    { value: 'TELFAIR', label: 'TELFAIR' },
    { value: 'TERRELL', label: 'TERRELL' },
    { value: 'THOMAS', label: 'THOMAS' },
    { value: 'TIFT', label: 'TIFT' },
    { value: 'TOOMBS', label: 'TOOMBS' },
    { value: 'TOWNS', label: 'TOWNS' },
    { value: 'TREUTLEN', label: 'TREUTLEN' },
    { value: 'TROUP', label: 'TROUP' },
    { value: 'TURNER', label: 'TURNER' },
    { value: 'TWIGGS', label: 'TWIGGS' },
    { value: 'UNION', label: 'UNION' },
    { value: 'UPSON', label: 'UPSON' },
    { value: 'WALKER', label: 'WALKER' },
    { value: 'WALTON', label: 'WALTON' },
    { value: 'WARE', label: 'WARE' },
    { value: 'WARREN', label: 'WARREN' },
    { value: 'WAYNE', label: 'WAYNE' },
    { value: 'WEBSTER', label: 'WEBSTER' },
    { value: 'WHEELER', label: 'WHEELER' },
    { value: 'WHITE', label: 'WHITE' },
    { value: 'HABERSHAM', label: 'HABERSHAM' },
    { value: 'STEPHENS', label: 'STEPHENS' },
    { value: 'WHITFIELD', label: 'WHITFIELD' },
    { value: 'WILCOX', label: 'WILCOX' },
    { value: 'WILKES', label: 'WILKES' },
    { value: 'WILKINSON', label: 'WILKINSON' },
    { value: 'WORTH', label: 'WORTH' }
  ];
  
  export const clientstatus =[
    {value: 'ACTIVE', label:'Active'},
    {value: 'IN_ACTIVE', label:'In Active'},
    {value: 'PENDING_AUTHORIZATION', label:'Pending Authorization'},
    {value: 'PENDING_REFERRAL', label:'Pending Referral'},
    {value: 'PENDING_AUTHORIZATION_AND_REFERRAL', label:'Pending Authorization and Referral'},
  ]